### ISSUE TITLE
Do not delete "codes" folder when updating

### ISSUE THREAD

**Issue by EpicLPer** [BullyWiiPlaza/Gecko-U-Updater#1]
When updating even tho JGecko is already present in the Downloaded folder it'll wipe the whole folder before. This also wipes the codes you've manually typed in or imported.

**Comment by BullyWiiPlaza** [comment]
This is normal, you're supposed to move it to somewhere else on your PC.

**Comment by EpicLPer** [comment]
This is not mentioned anywhere tho and you won't get a warning that this happened. It wiped my codes that I typed in for over 3 hours since nobody provided an importable file.

Happily I had a backup but at least mention it somewhere or make an update that warns you that it'll overwrite the whole folder when it detects a code folder.

**Comment by BullyWiiPlaza** [comment]
Yeah, I see now. I will not make it wipe anything anymore and just replace updated files. This should be safer for users.

EDIT:
Done, now all files will be replaced when there is an update and never deleted.
